pinctrl: pic64gx-gpio2: Add REGMAP_MMIO dependency
BugLink: https://bugs.launchpad.net/bugs/2074082

In line with other drivers depending on REGMAP_*, select the required
symbol to prevent a linker error when building with COMPILE_TEST=y:

ld: drivers/pinctrl/pinctrl-pic64gx-gpio2.o: in function `pic64gx_gpio2_probe':
pinctrl-pic64gx-gpio2.c:315:(.text+0x198): undefined reference to `__devm_regmap_init_mmio_clk'

Fixes: 38cf9d641314 ("pinctrl: add pic64gx "gpio2" pinmux driver")
Signed-off-by: Sander Vanheule <sander@svanheule.net>
Signed-off-by: Linus Walleij <linusw@kernel.org>
(cherry picked from commit bc277212b41ade2137b6278db24652d0847e9a91)
Signed-off-by: Emil Renner Berthing <emil.renner.berthing@canonical.com>